config/routes.rb
ShoppingList::Application.routes.draw do
  
  get "home/index"

  resources :user_sessions
  match 'login', :to => 'user_sessions#new', :as => "login"
  match 'logout', :to => 'user_sessions#destroy', :as => "logout"

  resources :users

  resources :list_items

  resources :lists

  root :to=> "home#index"

end

app/models/list.rb
class List < ActiveRecord::Base

	has_many :list_items, :dependent => :destroy
	
	#Displays nested list items if they are not blank
	accepts_nested_attributes_for :list_items, :reject_if => lambda { |a| a[:list_item_name].blank?}, :allow_destroy => true
	
	validates_uniqueness_of :list_name
	
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # GET /lists
  # GET /lists.xml
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.xml
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.xml
  def new
    @list = List.new
	#3.times { @list.list_items.build } #automatically puts 3 empty fields on the list

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
	#3.times { @list.list_items.build } #automatically puts 3 empty fields on the list
  end

  # POST /lists
  # POST /lists.xml
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to(@list, :notice => 'List was successfully created.') }
        format.xml  { render :xml => @list, :status => :created, :location => @list }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.xml
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to(@list, :notice => 'List was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.xml
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to(lists_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_name %><br />
    <%= f.text_field :list_name %>
  </div>
  <div class="field">
    <%= f.label :list_description %><br />
    <%= f.text_field :list_description %>
  </div>
  
  <table class="fields">
    <tr>
      <th>Item</th>
	  <th>Brand</th>
	  <th>Size</th>
	  <th>Remove?</th>
	</tr>
    <%= f.fields_for :list_items do |lister| %>
      <tr class="fields">
	    <td><%= lister.text_field :list_item_name %></td>
		<td><%= lister.text_field :list_item_brand %></td>
		<td><%= lister.text_field :list_item_size %></td>
		<%# Calls helpers\application_helper function to remove list_items %>
		<td><%= lister.hidden_field :_destroy %>
		     <%= link_to_remove_fields "Remove", lister %></td>
	  </tr>
	<% end %>
 </table>
 
	<p><%= link_to_add_fields "Add New Item", f, :list_items %></p>
	
   
   
   
   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_list_items.html.erb
   <table>
    <tr>
      <th>Item</th>
	  <th>Brand</th>
	  <th>Size</th>
	  <th>Remove?</th>
	</tr>
    <% f.fields_for :list_items do |lister| %>
      <tr>
	    <td><%= lister.text_field :list_item_name %></td>
		<td><%= lister.text_field :list_item_brand %></td>
		<td><%= lister.text_field :list_item_size %></td>
		<td><%= lister.check_box :_destroy %></td>
	  </tr>
	<% end %>
   </table>

app/views/lists/_list_items_fields.html.erb
<td><%= f.text_field :list_item_name %></td>
<td><%= f.text_field :list_item_brand %></td>
<td><%= f.text_field :list_item_size %></td>
<td><%= f.text_field :list_item_size %></td>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', :back %>

app/views/lists/index.html.erb
<h1>Shopping Lists</h1>

<table>
  <tr>
    <th>List name</th>
    <th>List description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><%= list.list_name %></td>
    <td><%= list.list_description %></td>
    <td><%= link_to 'Show', list %></td>
    <td><%= link_to 'Edit', edit_list_path(list) %></td>
    <td><%= link_to 'Destroy', list, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List', new_list_path %> | <%= link_to 'Back', :back %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<!-- p id="notice"><%= notice %></p -->

<p>
  <b>List name:</b>
  <%= @list.list_name %>
</p>

<p>
  <b>List description:</b>
  <%= @list.list_description %>
</p>

<% if @list.list_items %>
  <table>
    <tr>
      <th>Item</th>
	  <th>Brand</th>
	  <th>Size</th>
	</tr>
    <% for list_item in @list.list_items %>
      <tr>
	    <td><%= list_item.list_item_name %></td>
		<td><%= list_item.list_item_brand %></td>
		<td><%= list_item.list_item_size %></td>
	  </tr>
    <% end %>
  </table>
<% end %>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', :back %>