config/routes.rb
ShoppingList::Application.routes.draw do
  
  get "home/index"

  resources :user_sessions
  match 'login', :to => 'user_sessions#new', :as => "login"
  match 'logout', :to => 'user_sessions#destroy', :as => "logout"

  resources :users

  resources :list_items

  resources :lists

  root :to=> "home#index"

end

app/models/list_item.rb
class ListItem < ActiveRecord::Base

	belongs_to :list
	
	#validates_uniqueness_of :list, :list_item

end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  # GET /list_items
  # GET /list_items.xml
  def index
    @list_items = ListItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @list_items }
    end
  end

  # GET /list_items/1
  # GET /list_items/1.xml
  def show
    @list_item = ListItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @list_item }
    end
  end

  # GET /list_items/new
  # GET /list_items/new.xml
  def new
    @list_item = ListItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @list_item }
    end
  end

  # GET /list_items/1/edit
  def edit
    @list_item = ListItem.find(params[:id])
  end

  # POST /list_items
  # POST /list_items.xml
  def create
    @list_item = ListItem.new(params[:list_item])

    respond_to do |format|
      if @list_item.save
        format.html { redirect_to(@list_item, :notice => 'List item was successfully created.') }
        format.xml  { render :xml => @list_item, :status => :created, :location => @list_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @list_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /list_items/1
  # PUT /list_items/1.xml
  def update
    @list_item = ListItem.find(params[:id])

    respond_to do |format|
      if @list_item.update_attributes(params[:list_item])
        format.html { redirect_to(@list_item, :notice => 'List item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @list_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.xml
  def destroy
    @list_item = ListItem.find(params[:id])
    @list_item.destroy

    respond_to do |format|
      format.html { redirect_to(list_items_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/views/list_items/_form.html.erb
<%= form_for(@list_item) do |f| %>
  <% if @list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_item.errors.count, "error") %> prohibited this list_item from being saved:</h2>

      <ul>
      <% @list_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_item_name %><br />
    <%= f.text_field :list_item_name %>
  </div>
  <div class="field">
    <%= f.label :list_item_brand %><br />
    <%= f.text_field :list_item_brand %>
  </div>
  <div class="field">
    <%= f.label :list_item_size %><br />
    <%= f.text_field :list_item_size %>
  </div>
  <div class="field">
    <%= f.label :list_id %><br />
    <%= f.text_field :list_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_items/edit.html.erb
<h1>Editing list_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_item %> |
<%= link_to 'Back', :back %>

app/views/list_items/index.html.erb
<h1>Listing list_items</h1>

<table>
  <tr>
    <th>List item name</th>
    <th>List item brand</th>
    <th>List item size</th>
    <th>List</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @list_items.each do |list_item| %>
  <tr>
    <td><%= list_item.list_item_name %></td>
    <td><%= list_item.list_item_brand %></td>
    <td><%= list_item.list_item_size %></td>
    <td><%= list_item.list_id %></td>
    <td><%= link_to 'Show', list_item %></td>
    <td><%= link_to 'Edit', edit_list_item_path(list_item) %></td>
    <td><%= link_to 'Destroy', list_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List item', new_list_item_path %>

app/views/list_items/new.html.erb
<h1>New list_item</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/list_items/show.html.erb
<!-- p id="notice"><%= notice %></p -->

<p>
  <b>List item name:</b>
  <%= @list_item.list_item_name %>
</p>

<p>
  <b>List item brand:</b>
  <%= @list_item.list_item_brand %>
</p>

<p>
  <b>List item size:</b>
  <%= @list_item.list_item_size %>
</p>

<p>
  <b>List:</b>
  <%= @list_item.list_id %>
</p>


<%= link_to 'Edit', edit_list_item_path(@list_item) %> |
<%= link_to 'Back', :back %>