config/routes.rb
ShoppingList::Application.routes.draw do
  
  get "home/index"

  resources :user_sessions
  match 'login', :to => 'user_sessions#new', :as => "login"
  match 'logout', :to => 'user_sessions#destroy', :as => "logout"

  resources :users

  resources :list_items

  resources :lists

  root :to=> "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingList</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="outer-body">
  <% if current_user %>
        <div id="user_nav">
	     <%= "Welcome, #{current_user.username}!" %>&nbsp;&nbsp;
	     <%= link_to "Edit Profile", edit_user_path(current_user) %> | 
	     <%= link_to "Logout", logout_path %>
		</div>
  <% else %>
         <div id="user_nav"><%= link_to "Login", login_path %> (New user? <%= link_to "Register!", new_user_path %>)</div>
  <% end %>
  
  <div id="menu-bar">
     <div id="menu-item">
	 <%= link_to 'Home', root_url, { :title => 'Go to home page'} %>
	 <% if current_user %>
	    <%= link_to 'Lists', lists_url, { :title => 'Go to lists'} %>
	 <% end %>
	 </div>
  </div>
  

  <div id="shopping-list-box">
    <p id="notice"><%= notice %></p>
    <%= yield %>

  </div> <!-- end shopping-list-box -->

  <div id="outer-body-bottom-center">
     <script type="text/javascript" language="javascript">
     <!-- Begin
	    writeBottom("No");
     //-->
     </script>
  </div> <!-- end outer-body-bottom-center -->


<div> <!--end outer-body --></body>
</html>